name: Update README with Markdown Stats

on:
  push:
    branches: [main]  # main 브랜치 푸시 시 작동
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 사용 중인 Node 버전

      - name: Install dependencies (if needed)
        run: npm ci || npm install

      - name: Run create-readme script
        run: node create-readme.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: 자동으로 README 업데이트" || echo "No changes to commit"
          git push
